Change title from 'My App' to current working title of the game. Fixes issue #93.
spring2017gamestudio/prairie-creek pull request #95
Opened 2017-04-12 18:58 UTC by drsiscoe

2017-04-12 19:36 UTC, doctor-g requested changes

2017-04-12 19:36 UTC, doctor-g commented on index.html
>      <meta name="description" content="My App description">
Right under the title, we have a meta description tag that still just calls it "My App". Let's bring all this boilerplate code up to snuff so we don't have conflicting ideas in the source code.

2017-04-12 19:41 UTC, drsiscoe commented on index.html
>      <meta name="description" content="My App description">
Whoops. Must have overlooked it. I'm at work now so I'll just have to fix this when I get done tonight

2017-04-13 11:00 UTC, doctor-g approved these changes

2017-04-13 12:31 UTC, merged